import { faker } from "@faker-js/faker";
import type { Deal, LineItem, LineItemType, PipelineStage } from "@/shared/types/deal";
import { sumLineItems } from "@/shared/utils/line-items";

const STAGES: PipelineStage[] = ["prospect", "lead", "opportunity", "deal"];
const LINE_ITEM_TYPES: LineItemType[] = ["product", "service"];

function buildSeedLineItem(): LineItem {
  return {
    // Never a sequential counter or array index (research/PITFALLS.md
    // Pitfall 1/5) — same id convention as Deal.id.
    id: faker.string.uuid(),
    productOrService: faker.commerce.productName(),
    sku: faker.string.alphanumeric(8).toUpperCase(),
    units: faker.number.int({ min: 1, max: 20 }),
    unitPrice: faker.number.int({ min: 50, max: 5_000 }),
    type: faker.helpers.arrayElement(LINE_ITEM_TYPES),
  };
}

function buildSeedDeal(): Deal {
  const pipelineStage = faker.helpers.arrayElement(STAGES);
  // ~15% of seed deals are marked lost; never generate "won" this phase —
  // 01-RESEARCH.md Open Question 2 defers the explicit won-transition to
  // Phase 3, so all non-lost deals (including "deal" stage) stay "open".
  const isLost = faker.datatype.boolean({ probability: 0.15 });

  // 0-4 line items per deal (DEAL-04/DEAL-05 seed data). When non-empty, the
  // deal's value is set to the computed sum so seeded deals start in the
  // auto-tracked (non-overridden) state; an empty array leaves the existing
  // independent random value generation below unchanged.
  const lineItemCount = faker.number.int({ min: 0, max: 4 });
  const lineItems: LineItem[] =
    lineItemCount === 0
      ? []
      : Array.from({ length: lineItemCount }, buildSeedLineItem);

  return {
    id: faker.string.uuid(),
    name: faker.company.buzzPhrase(),
    company: faker.company.name(),
    value:
      lineItems.length > 0
        ? sumLineItems(lineItems)
        : faker.number.int({ min: 5_000, max: 250_000 }),
    owner: faker.person.fullName(),
    closeDate: faker.date.soon({ days: 90 }).toISOString(),
    pipelineStage,
    outcome: isLost ? "lost" : "open",
    createdAt: faker.date.recent({ days: 60 }).toISOString(),
    lineItems,
  };
}

/**
 * 40 fictional deals distributed across the 4 pipelineStage values, ~15%
 * marked lost. Every `id` is a `faker.string.uuid()` — never a sequential
 * counter or array index (research/PITFALLS.md Pitfall 1/5). Every field is
 * generated by faker's fictional generators — never real prospect/company/
 * person data, even for internal demos.
 */
export const seedDeals: Deal[] =
  typeof faker.helpers.multiple === "function"
    ? faker.helpers.multiple(buildSeedDeal, { count: 40 })
    : Array.from({ length: 40 }, buildSeedDeal);
