import { faker } from "@faker-js/faker";
import type { Deal, PipelineStage } from "@/shared/types/deal";

const STAGES: PipelineStage[] = ["prospect", "lead", "opportunity", "deal"];

function buildSeedDeal(): Deal {
  const pipelineStage = faker.helpers.arrayElement(STAGES);
  // ~15% of seed deals are marked lost; never generate "won" this phase —
  // 01-RESEARCH.md Open Question 2 defers the explicit won-transition to
  // Phase 3, so all non-lost deals (including "deal" stage) stay "open".
  const isLost = faker.datatype.boolean({ probability: 0.15 });

  return {
    id: faker.string.uuid(),
    name: faker.company.buzzPhrase(),
    company: faker.company.name(),
    value: faker.number.int({ min: 5_000, max: 250_000 }),
    owner: faker.person.fullName(),
    closeDate: faker.date.soon({ days: 90 }).toISOString(),
    pipelineStage,
    outcome: isLost ? "lost" : "open",
    createdAt: faker.date.recent({ days: 60 }).toISOString(),
  };
}

/**
 * 40 fictional deals distributed across the 4 pipelineStage values, ~15%
 * marked lost. Every `id` is a `faker.string.uuid()` — never a sequential
 * counter or array index (research/PITFALLS.md Pitfall 1/5). Every field is
 * generated by faker's fictional generators — never real prospect/company/
 * person data, even for internal demos.
 */
export const seedDeals: Deal[] =
  typeof faker.helpers.multiple === "function"
    ? faker.helpers.multiple(buildSeedDeal, { count: 40 })
    : Array.from({ length: 40 }, buildSeedDeal);
